<?php

namespace Tests\Feature;

use App\Server;
use App\Type;
use App\Version;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\SeededTest;
use Tests\TestCase;

class TypeTest extends SeededTest
{
    protected $type;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->type = Type::create(['slug'=>'test-type','name'=>'Test type']);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testServersRelation()
    {
        $servers = Server::limit(10)->get();
        $servers->each(function (Server $server){
            $server->types()->attach($this->type);
        });
        $this->assertEmpty($servers->diff($this->type->servers));
    }

    public function testToCheckBoxes(){
        $checkboxes = Type::toCheckboxes();
        $this->assertIsArray($checkboxes);
        $this->assertArrayHasKey('name', $checkboxes[0]);
    }
}
